-- Q1 Find the total number of customers
SELECT COUNT(*) AS total_customers FROM customers;

-- Q2 Count total employees
SELECT COUNT(*) AS total_employees FROM employees;

-- Q3 Find total number of products
SELECT COUNT(*) AS total_products FROM products;

-- Q4 Calculate total revenue from all orders
SELECT SUM(total_amount) AS total_sales FROM orders;

-- Q5 Find average order value
SELECT AVG(total_amount) AS average_order_value FROM orders;

-- Q6 Find highest order amount
SELECT MAX(total_amount) AS highest_order FROM orders;

-- Q7 Find lowest order amount
SELECT MIN(total_amount) AS lowest_order FROM orders;

-- Q8 Find how many orders are Completed, Pending, and Cancelled.
SELECT order_status, COUNT(*) AS total_orders FROM orders
GROUP BY order_status;

-- Q9 Calculate sales by payment method
SELECT payment_method, SUM(total_amount) AS total_sales FROM orders
GROUP BY payment_method;

-- Q10 Count employees by designation
SELECT designation, COUNT(*) AS employee_count FROM employees
GROUP BY designation;

-- Q11 Count employees in each store
SELECT store_id, COUNT(*) AS employee_count FROM employees
GROUP BY store_id;

-- Q12 Calculate average salary by designation
SELECT designation, AVG(salary) AS average_salary FROM employees
GROUP BY designation;

-- Q13 Find maximum salary by designation
SELECT designation, MAX(salary) AS highest_salary FROM employees
GROUP BY designation;

-- Q14 Find minimum salary by designation
SELECT designation, MIN(salary) AS lowest_salary FROM employees
GROUP BY designation;

-- Q15 Count products in each category
SELECT category_id, COUNT(*) AS product_count FROM products
GROUP BY category_id;

-- Q16 Find average selling price by category
SELECT category_id, AVG(selling_price) AS average_price FROM products
GROUP BY category_id;

-- Q17 Find total quantity sold for each product
SELECT product_id, SUM(quantity) AS total_quantity_sold FROM order_items
GROUP BY product_id;

-- Q18 Calculate revenue generated by each product
SELECT product_id, SUM((quantity * unit_price) - discount) AS product_revenue
FROM order_items
GROUP BY product_id;

-- Q19 Find designations having more than 10 employees
SELECT designation, COUNT(*) AS employee_count FROM employees
GROUP BY designation
HAVING COUNT(*) > 10;

-- Q20 Find stores with total sales greater than 10000
SELECT store_id, SUM(total_amount) AS total_sales FROM orders
GROUP BY store_id
HAVING SUM(total_amount) > 10000;

-- Q21 Find payment methods with more than 2 transactions
SELECT payment_method, COUNT(*) AS transaction_count FROM orders
GROUP BY payment_method
HAVING COUNT(*) > 2;

-- Q22 Find categories having more than 5 products
SELECT category_id, COUNT(*) AS total_products FROM products 
GROUP BY category_id
HAVING COUNT(*) > 5;

-- Q23 Find monthly sales
SELECT MONTHNAME(order_date) AS sales_month, SUM(total_amount) AS monthly_sales FROM orders
GROUP BY MONTHNAME(order_date);

-- Q24 Find yearly sales
SELECT YEAR(order_date) AS sales_year, SUM(total_amount) AS yearly_sales FROM orders
GROUP BY YEAR(order_date);

-- Q25 Count orders by year and status
SELECT YEAR(order_date) AS order_year, order_status, COUNT(*) AS total_orders FROM orders
GROUP BY YEAR(order_date), order_status; 
